<?php

namespace App\Filament\Resources;

use App\Filament\Resources\KategoriPemasukkanResource\Pages;
use App\Filament\Resources\KategoriPemasukkanResource\RelationManagers;
use App\Models\KategoriPemasukkan;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class KategoriPemasukkanResource extends Resource
{
    protected static ?string $model = KategoriPemasukkan::class;

    protected static ?string $navigationIcon = 'heroicon-o-tag';
    protected static ?string $navigationGroup = 'Manajemen Master';

    public static function getNavigationLabel(): string
    {
        return 'Kategori Pemasukkan';
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('kode')
                    ->label('Kode')
                    ->disabled() 
                    ->placeholder('Generated By System') 
                    ->unique('mm_kategori_pemasukkan', 'kode'),

                Forms\Components\TextInput::make('nama')
                    ->label('Nama')
                    ->required(),

                Forms\Components\Textarea::make('keterangan')
                    ->label('Keterangan'),

                Forms\Components\Hidden::make('id')
                    ->default(fn () => Str::uuid()->toString())
                    ->required(),
                
                Forms\Components\Hidden::make('deleted')
                    ->default(false),

                Forms\Components\Hidden::make('created_by')
                    ->default(fn () => Auth::user()->name),

                Forms\Components\Hidden::make('created_date')
                    ->default(now()),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('kode')
                    ->label('Kode')
                    ->sortable()
                    ->searchable(),

                Tables\Columns\TextColumn::make('nama')
                    ->label('Nama')
                    ->sortable()
                    ->searchable(),

                Tables\Columns\TextColumn::make('created_by')
                    ->label('Dibuat Oleh'),
            ])

            ->query(KategoriPemasukkan::where('deleted', false))

            ->filters([])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make()
                    ->action(function ($record) {
                        $record->update([
                            'deleted' => true,
                            'updated_by' => Auth::user()->name,
                            'updated_date' => now(),
                        ]);
                    })
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make()
                    ->action(function ($records) {
                        foreach ($records as $record) {
                            $record->update([
                                'deleted' => true,
                                'updated_by' => Auth::user()->name,
                                'updated_date' => now(),
                            ]);
                        }
                    }),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListKategoriPemasukkans::route('/'),
            'create' => Pages\CreateKategoriPemasukkan::route('/create'),
            'edit' => Pages\EditKategoriPemasukkan::route('/{record}/edit'),
        ];
    }
}
